version: "3"

services:
  bot:
    build: .
    container_name: bot_download_wf
    environment:
      - CHROME_HOST=bot_download_wf_chrome
      - USER=45522077
      - PSW=Le@onv35/*
    volumes:
      - ./app:/app
      - ./Downloads:/app/Downloads
    depends_on:
      - bot_download_wf_chrome
    networks:
      - selenium_net

  bot_download_wf_chrome:
    image: selenium/standalone-chrome
    container_name: bot_download_wf_chrome
    volumes:
      - /dev/shm:/dev/shm
      - ./Downloads:/home/seluser/Downloads     
    ports:
      - "4472:4444"  # Puerto para Selenium
      - "7927:7900"  # Puerto para VNC
      - "9249:9222"  # Puerto para DevTools
    environment:
      - SE_VNC_NO_PASSWORD=1
    networks:
      - selenium_net

networks:
  selenium_net:
    driver: bridge
