version: "3.8"

services:
  bot:
    build: .
    container_name: python_bot
    environment:
      - CHROME_HOST=bot_chrome
      - USER=45522077
      - PSW=Le@onv35/*
    volumes:
      - ./app:/app
      - ./Downloads:/app/Downloads
    depends_on:
      - bot_chrome
    networks:
      - selenium_net
    restart: unless-stopped

  bot_chrome:
    image: selenium/standalone-chrome
    container_name: bot_chrome
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
      - ./Downloads:/home/seluser/Downloads
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - selenium_net
    restart: unless-stopped

networks:
  selenium_net:
    driver: bridge
